## Introduction to Python Exercises

![](https://github.com/rpi-techfundamentals/hm-01-starter/blob/master/notsaved.png?raw=1)

**WARNING!!!  If you see this icon on the top of your COLAB sesssion, your work is not saved automatically.**

**Save your working file in Google drive so that all changes will be saved as you work. MAKE SURE that your final version is saved to GitHub.** 

Before you turn this in, make sure everything runs as expected. First, restart the kernel (in the menu, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment.

**You may find it useful to go through the notebooks from the course materials when doing these exercises.**

**If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation.**

In [1]:
files = "https://github.com/rpi-techfundamentals/hm-02-starter/raw/master/files.zip"
!pip install git+https://github.com/data-8/Gofer-Grader && wget $files && unzip -o files.zip

  Cloning https://github.com/data-8/Gofer-Grader to /tmp/pip-req-build-07n1ux6h
  Running command git clone -q https://github.com/data-8/Gofer-Grader /tmp/pip-req-build-07n1ux6h
  Created wheel for gofer-grader: filename=gofer_grader-1.0.9-cp36-none-any.whl size=10115 sha256=4e383de55bca19513e1e7bb398f7bb0d698ab93fb30b488f50267c6744222aa2
  Stored in directory: /tmp/pip-ephem-wheel-cache-g6g7klf5/wheels/9e/62/24/8563ae039051d6ba979557d1766bfebbda5dd08f8572e3e35d
Successfully built gofer-grader
--2019-09-19 22:22:58--  https://github.com/rpi-techfundamentals/hm-02-starter/raw/master/files.zip
Resolving github.com (github.com)... 192.30.253.113
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rpi-techfundamentals/hm-02-starter/master/files.zip [following]
--2019-09-19 22:22:58--  https://raw.githubusercontent.com/rpi-techfundamentals/hm-02-starter/master/files.zip
Resolvin

In [0]:
#This loads the grading software.  If you later get a "failed to import OK.py" you need to rerun.
from client.api.notebook import Notebook
ok = Notebook('hm02.ok')
_ = ok.auth(inline=True)

## Exercise-Packages

This creates an Numpy array. Numpy is a common package that we will use to work with arrays. You can read more about Numpy [here](http://www.numpy.org/). 

```
a = np.array([2,3,4])
print(a)
```

To get this to work, you will have to make sure that the numpy(np) package is installed. 

(1) Verify that Numpy is installed. How did you know?  
Describe how you would you install it if it wasn't installed?


In [0]:
man1="""
If we don't install Numpy package and import it as np before, the command lines will result in an error: name 'np' is not defined.
If importing successfully, we can print out the array of rank 1 [2 3 4]. 
"""

(2) Fix the cell below so that `a` is a `numpy` array.

In [4]:
#Fix this code of q2. 
import numpy as np

a = np.array([5,6,7,8])
print(a, type(a))


[5 6 7 8] <class 'numpy.ndarray'>


In [5]:
_ = ok.grade('q02')

(3) Create a numpy array `b` with the values `12, 13, 14, 15`.



In [6]:
#<insert q3 code here>
b = np.array([12, 13, 14, 15])
print(b)

[12 13 14 15]


In [7]:
_ = ok.grade('q03')

## Exercise - Operations on Variables

(4) Describe what happens when you multiply an integer times a boolean? 
What is the resulting type? Provide examples.


In [0]:
#You must assign your answer to q4_answer. 
man4="""
When we multiply an int with a boolean, the boolean will be converted to an int, with "True" becoming 1 and "False" becoming 0. The data type of the multiplication result is an interger.
For example, When we set:
a = False
b = 2
c = a * b
print(c)            # 0
print(type(c))      # <class 'int'>

We can find that "c" will be an int with value 0 because "a" is converted into an int with value 0. 

On the other side, if:
a = True
b = 2
c = a * b
print(c)            # 2
print(type(c))      # <class 'int'>


"c" will be an int with value = 2 because "a" becomes an int with value 1.
"""

(5) Describe happens when you try to multiply an integer value times a null?

In [0]:
man5="""
There will be an error: unsupported operand type(s) for *: 'NoneType' and 'int'. We can't multiply with an empty-state variable.
"""


(6) Take 5 to the power of 4 and assign it to a variable `c`. Then transform the variable `c` to a type `float`. 

In [10]:
#<insert q6 code here>
c = float(5**4)
print(c)

625.0


In [11]:
_ = ok.grade('q06')

## Exercise-Lists
Hint: [This link is useful.](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) as is the process of tab completion (using tab to find available methods of an object).

(7) Create a list `elist1` with the following values `1,2,3,4,5`.<br>


In [12]:
#<insert q7 code here>
elist1 = [1,2,3,4,5]
print(elist1)

[1, 2, 3, 4, 5]


In [13]:
_ = ok.grade('q07')

(8) Create a new list `elist2` by first creating a copy of `elist1` and then reversing the order.

*HINT, remember there is a specific function to copy a list.* 


In [14]:
#<insert q8 code here>
elist2 = elist1.copy()
elist2.reverse()
print(elist2)

[5, 4, 3, 2, 1]


In [15]:
_ = ok.grade('q08')

(9) Create a new list `elist3` by first creating a copy of `elist1` and then adding `7, 8, 9` to the end. (Hint: Search for a different function if appending doesn't work.) 

In [16]:
#<insert q9 code here>
elist3 = elist1.copy()
elist3.extend([7,8,9])
print(elist3)

[1, 2, 3, 4, 5, 7, 8, 9]


In [17]:
_ = ok.grade('q09')

(10) Create a new list `elist4` by first creating a copy of `elist3` and then insert `6` between `5` and `7`.

In [18]:
#<insert q10 code here>
elist4 = elist3.copy()
elist4.insert(5,6)
print(elist4)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [19]:
_ = ok.grade('q10')

## Exercise-Sets/Dictionary

This [link to documentation on sets](https://docs.python.org/3/tutorial/datastructures.html#sets) may be useful.

(11) Create a set `eset1` with the following values (1,2,3,4,5).


In [20]:
#<insert q11 code here>
eset1 = set(range(1,6))
print(eset1)

{1, 2, 3, 4, 5}


In [21]:
_ = ok.grade('q11')


(12) Create a new set `eset2` the following values (1,3,6).



In [22]:
#<insert q12 code here>
eset2 = set([1,3,6])
print(eset2)

{1, 3, 6}


In [23]:
_ = ok.grade('q12')

(13) Create a new set `eset3` that is `eset1-eset2`.



In [24]:
#<insert q13 code here>
eset3 = eset1 - eset2
print(eset3)

{2, 4, 5}


In [25]:
_ = ok.grade('q13')

(14) Create a new set `eset4` that is the union of `eset1+eset2`.


In [26]:
#<insert q14 code here>
eset4 = eset1 | eset2
print(eset4)

{1, 2, 3, 4, 5, 6}


In [27]:
_ = ok.grade('q14')


(15) Create a new set `eset5` that includes values that are in both `eset1` and `eset2` (intersection).



In [28]:
#<insert q15 code here>
eset5 = eset1 & eset2
print(eset5)

{1, 3}


In [29]:
_ = ok.grade('q15')

(16) Create a new dict `edict1` with the following keys and associated values: st1=45; st2=32; st3=40; st4=31.

*Hint: There is a good section on dictionaries [here](https://docs.python.org/3/tutorial/datastructures.html#dictionaries).


In [30]:
#<insert q16 code here>
edict1 = {"st1": 45, "st2": 32, "st3": 40, "st4": 31}
print(edict1)

{'st1': 45, 'st2': 32, 'st3': 40, 'st4': 31}


In [31]:
_ = ok.grade('q16')


(17) Create a new variable `key1` where the value is equal to the value of dictionary edict1 with key `st3`.

In [32]:
#<insert q17 code here>
key1 = edict1["st3"]
print(key1)

40


In [33]:
_ = ok.grade('q17')

# Exercise-Numpy Array

(18) Create a new numpy array `nparray1` that is 3x3 and all the number 3 (should be integer type).



In [34]:
#<insert q18 code here>
nparray1 = np.full((3,3),3)
print(nparray1)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [35]:
_ = ok.grade('q18')


(19) Create a new variable `nparray1sum` that sums all of column 0.


In [36]:
#<insert q19 code here>
sliced_nparray1 = nparray1[:3,0]
nparray1sum = sliced_nparray1.sum()
print(nparray1sum)

9


In [37]:
_ = ok.grade('q19')

(20) Create a new variable `nparray1mean` that takes the average of column 0.


In [38]:
#<insert q20 code here>
nparray1mean = np.average(sliced_nparray1)
print(nparray1mean)

3.0


In [39]:
_ = ok.grade('q20')

(21) Create a new numpy array `nparray2` that selects only column 1 of `nparray1` (all rows).


In [40]:
#<insert q21 code here>
nparray2 = nparray1[:,1:2]
print(nparray2)

[[3]
 [3]
 [3]]


In [41]:
_ = ok.grade('q21')

(22) Create a new numpy array `nparray3` that is equal to `nparray1` times `2` (you should not alter `nparray1`).


In [42]:
#<insert q22 code here>
nparray3 = nparray1 * 2
print(nparray3)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [43]:
_ = ok.grade('q22')

(23) Create a new numpy array nparray4 that is a verticle stack of `nparray1` and `nparray3`.

In [44]:
#<insert q23 code here>
nparray4 = np.vstack((nparray1,nparray3))
print(nparray4)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [45]:
_ = ok.grade('q23')

## Exercise-Pandas

For these you will need to import the iris dataset. You should find the file `iris.csv` in the main directory.  

While we showed 2 ways of importing a csv, you should use the `read_csv` method of Pandas to load the csv into a dataframe called `df`. 


In [46]:
#Load iris.csv into a Pandas dataframe df here.
#Check out the first few rows with the head command. 
import pandas as pd
df= pd.read_csv('iris.csv')
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0    

(24) Create a variable `df_rows` that includes the number of rows in the `df` dataframe.

In [47]:
#<insert q24 code here>
df_rows = df.shape[0]
print(df_rows)

150


In [48]:
_ = ok.grade('q24')

(25) Create a new dataframe `df_train` that includes the first half of the `df` dataframe. Create a new dataframe `df_test` that includes the second half. 

In [49]:
#<insert q25 code here>
df_train = df[:75]
df_test = df[75:]
print(df_train)
print(df_test)

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
5            5.4          3.9           1.7          0.4      setosa
6            4.6          3.4           1.4          0.3      setosa
7            5.0          3.4           1.5          0.2      setosa
8            4.4          2.9           1.4          0.2      setosa
9            4.9          3.1           1.5          0.1      setosa
10           5.4          3.7           1.5          0.2      setosa
11           4.8          3.4           1.6          0.2      setosa
12           4.8          3.0           1.4          0.1      setosa
13           4.3          3.0     

In [50]:
_ = ok.grade('q25')

(26) Create a new Pandas Series `sepal_length` from the `sepal_length` column of the df dataframe.

In [51]:
#<insert q26 code here>
sepal_length = df['sepal_length']
print(sepal_length)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64


In [52]:
_ = ok.grade('q26')


(27) Using, the Iris dataset, find the mean of the `sepal_length` series in our sample and assign it to the `sepal_length_mean` variable. You should round the result to 3 digits after the decimal. 

```
#Round example
a=99.9999999999999
#For example, the following will round a to 2 digits.
b = round(a,2)   

```

In [53]:
#<insert q27 code here>

a = df.loc[:,"sepal_length"].mean()
sepal_length_mean = round(a,3)
print(sepal_length_mean)

5.843


In [54]:
_ = ok.grade('q27')

## Enter your Information
Enter your information.  This will run all tests to make sure that the assignment is complete. 

In [0]:
course="mgmt6560"   #course number
section="2"          #section 
first_name="Chi"   #For example, "jason"
last_name="Wang"    #For example, "kuruzovich"
student_id="chiwangchic"       #for example "kuruzj"
student_email="wangc24@rpi.edu"    #for example "kuruzj@rpi.edu"
collaborators = "No"  #You can speak with others regarding the assignment, but all typed work must be your own.

In [56]:
#This runs all tests. 
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]