In [0]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [0]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array((2,4,6))
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[2 4 6]


In [0]:
import numpy as np
a = np.array([[1,2,3,4],[5,4], [5,6,7,None]])
print(a.shape)

(3,)


In [0]:
import numpy as np
a = np.zeros((2,2))
print(a)

In [0]:
import numpy as np
b = np.ones((1,2))
print(b)

In [0]:
import numpy as np
c = np.eye((2))
d = a+c
print(d)

In [0]:
import numpy as np
b = np.random.random((2,2))
print(b)

In [0]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[:2,1:3])

b = a[:2, 1:3]

[[2 3]
 [6 7]]


In [0]:
import numpy as np
print(a[0, 1])
b[0, 0] = 7
print(a[0, 1]) 
print(a)


#A subset of an array is a view into the same data --> b[0, 0] is the same piece of data as a[0, 1] 

In [0]:
a = np.array([[1,2,3,4], [6,7,8,9]])

print(a.shape)

print(a[0,1:3])

print(a[:,2])



(2, 4)
[2 3]
[3 8]


In [0]:
import numpy as np
a = np.array([[1, 2, 3, 4,5], [5, 6, 7, 8,9], [9, 10, 11, 12,13], [13, 14, 15, 16,17]])
sliced_a=a[:2, ::2]
print(sliced_a)

[[1 3 5]
 [5 7 9]]


In [0]:
a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [0]:
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(a[[1,2,1,3],[1,0,2,3]])

[ 6  9  7 16]


In [0]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)

print(np.add(x, y))

In [0]:
print(x-y)

print(np.subtract(x, y))

In [0]:
print(np.sqrt(x))

In [0]:
import numpy as np

a = np.array([[1,2], [3,4]])

print(a)

print(a.T)

print(a.reshape(4,1))

In [0]:
import pandas as pd

Data =[1, 3, 5, 7, 9, 11, 13]
Index =['a', 'b', 'c', 'd', 'e', 'f', 'g']  

ser = pd.Series(Data, Index)  
print(ser)

In [0]:
import pandas as pd

Data =[1, 3, 5, 7, 9, 11, 13]
ser = pd.Series(Data)
print(ser)

Index =['a', 'b', 'c', 'd', 'e', 'f', 'g']  

new_ser = pd.Series(Data, Index)  
print(new_ser)

In [0]:
import pandas as pd

Data =[1, 3, 5, 7, 9, 11]
Index =['a', 'b', 'c', 'd', 'e', 'f', 'g']  

ser = pd.Series(Data, Index)  
print(ser)

In [0]:
import pandas as pd

Data =[1, 3, 5, 7, 9, 11, 13]
Index =['a', 'b', 'c', 'd', 'e', 'f']  

ser = pd.Series(Data, Index)  
print(ser)

In [0]:
Data =[[2, 3, 4], [5, 6, 7]]
ser = pd.Series(Data)

print(ser)

Index=['a', 'b']
ser_n = pd.Series(Data, Index)
print(ser_n)

In [0]:
import pandas as pd

dict1 ={'a':1, 'b':2, 'c':3, 'd':4} 
dict2 ={'a':5, 'b':6, 'c':7, 'd':8, 'e':9} 
Data = {'first':dict1, 'second':dict2} 
df = pd.DataFrame(Data) 

print(df)

In [0]:
import pandas as pd

dict1 ={'a':1, 'b':2, 'c':3, 'd':4} 
dict2 ={'a':5, 'b':6, 'c':7, 'd':8, 'e':9} 
Data = {'first':dict1, 'first':dict2} 
df = pd.DataFrame(Data) 

print(df)

In [0]:
import pandas as pd 
d1 =[[2, 3, 4], [5, 6, 7]] 
d2 =[[2, 4, 8], [1, 3, 9]] 
Data ={'first': d1, 'second': d2}   
df2d = pd.DataFrame(Data) 

print(df2d)

In [0]:
import pandas as pd

nlist=[1, 2, 3, 4, 5, 6]
df = pd.DataFrame(nlist)
print(df)



In [0]:
import pandas as pd

nlist=[1, 2, 3, 4, 5, 6]
df = pd.Dataframe(nlist)
print(df)


In [0]:
import pandas as pd
 
data = {'Name':['John', 'Jeff', 'Joe', 'Jess'],
        'Age':[25, 28, 27, 32],
        'Address':['Ohio', 'California', 'Arizona', 'New York'],
        'Qualification':['BS', 'MS', 'MS', 'Phd']}
 
df = pd.DataFrame(data)
 
print(df[['Name', 'Qualification']])

In [0]:
from google.colab import files
uploaded = files.upload()

In [0]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col="Name")

#print(data)

first=data.loc["Avery Bradley"]
second=data.loc["R.J. Hunter"]

print(first)
print("\n\n")
print(second)


In [0]:
import pandas as pd
data = pd.read_csv("nba.csv", index_col="Name")

first = data["Age"]
print(first)